### ISSUE TITLE
Issue with npm start after npm install

### ISSUE THREAD

**Issue by FarhatRV** [bradtraversy/react_webpack_starter#9]
`react_webpack_starter farhatrv$ npm start

> react_webpack_starter@1.0.0 start /Users/farhatrv/Documents/react_webpack_starter
> webpack-dev-server --mode development --open --hot

/Users/farhatrv/Documents/react_webpack_starter/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/Users/farhatrv/Documents/react_webpack_starter/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at Object.<anonymous> (/Users/farhatrv/Documents/react_webpack_starter/node_modules/webpack-dev-server/bin/webpack-dev-server.js:86:25)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react_webpack_starter@1.0.0 start: `webpack-dev-server --mode development --open --hot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react_webpack_starter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/farhatrv/.npm/_logs/2019-05-05T10_51_55_521Z-debug.log`

Getting the above error!

**Comment by FarhatRV** [comment]
Resolution: 

update webpack and webpack-cli version:

`"webpack": "^4.20.2",
    "webpack-cli": "^3.1.1",`
